require 'rake'

Gem::Specification.new do |s|
  s.name        = 'simbuddy'
  s.version     = '0.0.0'
  s.date        = '2013-12-04'
  s.summary     = "Interacts with iOS Simulator"
  s.description =<<-EOS
This tool reads files generated by an iOS application running within the simulator,
and saves them within the correponding XCode project's directory.
EOS
  s.authors     = ["Jeff Sember"]
  s.email       = 'jpsember@gmail.com'
  s.files = FileList['lib/**/*.rb',
                      'bin/*',
                      '[A-Z]*',
                      'test/**/*',
                      ]
  s.add_runtime_dependency 'trollop'
  s.add_runtime_dependency 'js_base'
  s.add_runtime_dependency 'backup_set'
  s.executables << 'simbuddy'
  s.homepage = 'http://www.cs.ubc.ca/~jpsember'
  s.test_files  = Dir.glob('test/*.rb')
  s.license     = 'MIT'
end

